### ISSUE TITLE
[Bug]: ingame story Log is empty with fix enabled

### ISSUE THREAD

**Issue by Vladsmesh** [Lyall/P3RFix#32]
with the modification activated, the game history log is empty

 v1.1.4, latest GamePass version
 
 
 UPD: the issue was solved after I started the game without fix, opened the log in the cutscene (it worked), saved, and restarted the game with the fix enabled, and the story log started working again.
 
 UPD2: after some cutscenes log is not working again.

**Comment by Lyall** [comment]
Hmm that's an odd one. I can't seem to replicate it on my end. Can you post your `P3RFix.log` file? It should be either next to `P3R.exe` or next to the launcher in the main game folder.

Also what might help is knowing where you were in the game when the bug happened. I'm still early game so you might be encountering something that breaks the log that I wouldn't find.

**Comment by Vladsmesh** [comment]
> Hmm that's an odd one. I can't seem to replicate it on my end. Can you post your `P3RFix.log` file? It should be either next to `P3R.exe` or next to the launcher in the main game folder.
> 
[P3RFix.log](https://github.com/Lyall/P3RFix/files/14408139/P3RFix.log)

> Also what might help is knowing where you were in the game when the bug happened. I'm still early game so you might be encountering something that breaks the log that I wouldn't find.

It happened at about the 18th hour of the game in the cutscene where you, Junpei and Yukari met in the dorm to discuss the information they found about the ghost at school (06.06 I guess?).

Maybe it's just a game bug unrelated to the fix?

**Comment by Lyall** [comment]
> It happened at about the 18th hour of the game in the cutscene where you, Junpei and Yukari met in the dorm to discuss the information they found about the ghost at school (06.06 I guess?).
>
> Maybe it's just a game bug unrelated to the fix?

Thanks for that info, I will try and verify myself when I get to that point. It's possible it's a game bug but hard to know. The two most likely parts of P3RFix that would effect something like that would be the Render Texture Resolution feature and the HUD Fix. If you still have access to the bugged part through a save or something you could try disabling those two features in `P3RFix.ini` and testing it. 

Otherwise, I apologise that it'll have to wait until I get to that point and see if I get the same issue. At least it's not something too majorly game breaking!

**Comment by Aelzaire** [comment]
Can confirm the same issue on my end.
had 1.1.2 installed, updated to 1.1.5 and the log disappeared, on the same day. I've played for a bit, currently on 07/23 but doesn't matter what day it is, it what happens, log remains empty.
not displaying weird, just says "EMPTY" when you pull it up.

**Comment by vicktorhu** [comment]
Same here with 1.1.5.
This is the log: [P3RFix.log](https://github.com/Lyall/P3RFix/files/14468276/P3RFix.log)

Switched back to 1.1.4 and it worked great again.

**Comment by Lyall** [comment]
> Same here with 1.1.5. This is the log: [P3RFix.log](https://github.com/Lyall/P3RFix/files/14468276/P3RFix.log)
> 
> Switched back to 1.1.4 and it worked great again.
> 
> Edit: I never have any problem with 1.1.4 and prior versions.

That's very interesting. Not a lot changed in v1.1.5. I'll have a look and see.

**Comment by Aelzaire** [comment]
I've noticed the past few days it's inconsistent. Sometimes the log doesn't work, other times it does. I know it works 100% on 1.1.2, I think the network skip change made in 1.1.4 might've had a hand, but this is purely a guess. Only thing I can think of that was a major change between the two versions.

**Comment by Lyall** [comment]
> I've noticed the past few days it's inconsistent. Sometimes the log doesn't work, other times it does. I know it works 100% on 1.1.2, I think the network skip change made in 1.1.4 might've had a hand, but this is purely a guess. Only thing I can think of that was a major change between the two versions.

That actually could make sense. The network skip bit works with some shared code for closing dialog boxes so perhaps that's what's happening. If that wasn't executing properly then it could be causing the log to "close" when it's opened.

**Comment by Lyall** [comment]
Okay I've rewritten how the dialog skipping part of the network skip functions.  Also put in a safeguard to ensure it only runs the required amount of times to skip the network dialog. Can anyone with this bug give this test build a try and see if it fixes it?

[P3RFix_v1.1.6_Xbox.zip](https://github.com/Lyall/P3RFix/files/14470514/P3RFix_v1.1.6_Xbox.zip)
[P3RFix_v1.1.6_Steam.zip](https://github.com/Lyall/P3RFix/files/14470513/P3RFix_v1.1.6_Steam.zip)

**Comment by Aelzaire** [comment]
> Okay I've rewritten how the dialog skipping part of the network skip functions. Also put in a safeguard to ensure it only runs the required amount of times to skip the network dialog. Can anyone with this bug give this test build a try and see if it fixes it?
> 
> [P3RFix_v1.1.6_Xbox.zip](https://github.com/Lyall/P3RFix/files/14470514/P3RFix_v1.1.6_Xbox.zip) [P3RFix_v1.1.6_Steam.zip](https://github.com/Lyall/P3RFix/files/14470513/P3RFix_v1.1.6_Steam.zip)

You're a legend! I'll test abd report back.

**Comment by Aelzaire** [comment]
First test seems to be working. I'll come back and update this if I notice anything else happening. Thanks, Lyall!

**Comment by Lyall** [comment]
This should be fixed in v1.1.6

**Comment by jerdunderscore** [comment]
Hello, this issue still occurs for me on latest v1.1.6. Using Windows with the Steam Version of the game. I have been playing for a few in game days (currently in the beginning of August) and nothing has shown up in text log. 

I have tried the following with no success:
Disabling Render Texture Resolution feature and the HUD Fix (as suggested before in this thread)
Reinstalling P3RFix.
Reverting to v1.1.2 fixed the issue, then updating again to v1.1.6 breaks it again.
Reinstalling P3R and then installing P3RFix.

I have included my log file. Thank you!

[P3RFix.log](https://github.com/Lyall/P3RFix/files/14551464/P3RFix.log)

**Comment by Lyall** [comment]
> Hello, this issue still occurs for me on latest v1.1.6. Using Windows with the Steam Version of the game. I have been playing for a few in game days (currently in the beginning of August) and nothing has shown up in text log.
> 
> I have tried the following with no success: Disabling Render Texture Resolution feature and the HUD Fix (as suggested before in this thread) Reinstalling P3RFix. Reverting to v1.1.2 fixed the issue, then updating again to v1.1.6 breaks it again. Reinstalling P3R and then installing P3RFix.
> 
> I have included my log file. Thank you!
> 
> [P3RFix.log](https://github.com/Lyall/P3RFix/files/14551464/P3RFix.log)

Hmm, can you verify if the problem still happens with the intro skip disabled in `P3RFix.ini`?

**Comment by aligg2509** [comment]
i know I'm not the dude you asked for confirming this but I'm also having the same bug happens on my playthrough so i might as well share my test results here

and yes i can confirm the bug isn't present when disabling the intro skip

here's my log btw 
[P3RFix.log](https://github.com/Lyall/P3RFix/files/14555248/P3RFix.log)

**Comment by aligg2509** [comment]
> > Hello, this issue still occurs for me on latest v1.1.6. Using Windows with the Steam Version of the game. I have been playing for a few in game days (currently in the beginning of August) and nothing has shown up in text log.
> > I have tried the following with no success: Disabling Render Texture Resolution feature and the HUD Fix (as suggested before in this thread) Reinstalling P3RFix. Reverting to v1.1.2 fixed the issue, then updating again to v1.1.6 breaks it again. Reinstalling P3R and then installing P3RFix.
> > I have included my log file. Thank you!
> > [P3RFix.log](https://github.com/Lyall/P3RFix/files/14551464/P3RFix.log)
> 
> Hmm, can you verify if the problem still happens with the intro skip disabled in `P3RFix.ini`?



i know I'm not the dude you asked for confirming this but I'm also having the same bug happens on my playthrough so i might as well share my test results here

and yes i can confirm the bug isn't present when disabling the intro skip

here's my log btw
[P3RFix.log](https://github.com/Lyall/P3RFix/files/14555277/P3RFix.log)

**Comment by jerdunderscore** [comment]
> > Hello, this issue still occurs for me on latest v1.1.6. Using Windows with the Steam Version of the game. I have been playing for a few in game days (currently in the beginning of August) and nothing has shown up in text log.
> > I have tried the following with no success: Disabling Render Texture Resolution feature and the HUD Fix (as suggested before in this thread) Reinstalling P3RFix. Reverting to v1.1.2 fixed the issue, then updating again to v1.1.6 breaks it again. Reinstalling P3R and then installing P3RFix.
> > I have included my log file. Thank you!
> > [P3RFix.log](https://github.com/Lyall/P3RFix/files/14551464/P3RFix.log)
> 
> Hmm, can you verify if the problem still happens with the intro skip disabled in `P3RFix.ini`?

Problem does not occur with intro fix disabled.

**Comment by Lyall** [comment]
That's frustrating, I wonder if there is some difference with the code on the Steam version. I still haven't been able to replicate the bug on my end but I only have access to the Xbox Gamepass version.

**Comment by Lyall** [comment]
Okay after looking at it again I was actually able to replicate the bug and I think I know what's causing it. Here is a test build with a potential fix.

[P3RFix_v1.1.6_Xbox.zip](https://github.com/Lyall/P3RFix/files/14588196/P3RFix_v1.1.6_Xbox.zip)
[P3RFix_v1.1.6_Steam.zip](https://github.com/Lyall/P3RFix/files/14588194/P3RFix_v1.1.6_Steam.zip)

**Comment by aligg2509** [comment]
> Okay after looking at it again I was actually able to replicate the bug and I think I know what's causing it. Here is a test build with a potential fix.
> 
> [P3RFix_v1.1.6_Xbox.zip](https://github.com/Lyall/P3RFix/files/14588196/P3RFix_v1.1.6_Xbox.zip) [P3RFix_v1.1.6_Steam.zip](https://github.com/Lyall/P3RFix/files/14588194/P3RFix_v1.1.6_Steam.zip)

Flawless dude
i can confirm that the issue doesn't occur on this build
Thanks Lyall ʕ⁠·⁠ᴥ⁠·⁠ʔ

**Comment by jerdunderscore** [comment]
Sorry for the delay.
I can confirm that the issue is resolved.
Thank you very much!

**Comment by Lyall** [comment]
Fixed in v1.1.7
