### ISSUE TITLE
[Bug]: Game crashes at startup

### ISSUE THREAD

**Issue by OffApparition** [Lyall/P3RFix#49]
## Issue Summary:

The game crashes at startup showing the UE crash reporter when using the mod.
I can run the game normally when not using the mod by excluding the `WINEDLLOVERRIDES="dsound=n,b" %command%` launch option.

![image](https://github.com/user-attachments/assets/db96f6a3-75bc-4deb-91fb-e7ef0e34ac58)

## P3RFix & Game Version Numbers:

Tried v1.2.2 and v1.2.3 of P3RFix and using the latest game version.

## Log Files:

[P3RFix.log](https://github.com/user-attachments/files/17034139/P3RFix.log)

I'm using a 7800X3D and an RX 7900XT on Linux.

## Reproduction:

1.  Click on Launch button in Steam
2.  Game crashes and UE4 crash reporter opens

**Comment by Wildikdog** [comment]
Funnily enough I was gonna put one up for this because I had the same issue, I found it didn't crash on 1.2.1, so I must imagine some regression happened with 1.2.2.

**Comment by slapjd** [comment]
Same issue here. For me, this seems to be caused by the developer console enabler. Turning it off lets the game launch, so maybe try that?

**Comment by bycEEE** [comment]
`v1.2.3` crashes for me on the Steam Deck. As suggested, disabling the developer console in the ini file does fix the crashing.

**Comment by Lyall** [comment]
Should be fixed in v1.2.4. The crash was likely coming from attempting to set a hotkey when the ConsoleKeys array was not initialised.

**Comment by slapjd** [comment]
Just tried 1.2.4 and the issue still mostly persists for me (disabling the dev console also still fixes it). The game has successfully (randomly) launched 3 times with the option enabled and I have verified that the console works under that case but the vast majority of the time it just crashes the game on startup.
Also, for clarity, I'm also on Linux with a Ryzen 7 3700X and a GTX 1080.

**Comment by Lyall** [comment]
> Just tried 1.2.4 and the issue still mostly persists for me (disabling the dev console also still fixes it). The game has successfully (randomly) launched 3 times with the option enabled and I have verified that the console works under that case but the vast majority of the time it just crashes the game on startup. Also, for clarity, I'm also on Linux with a Ryzen 7 3700X and a GTX 1080.

Can you try this test build? I've reworked the code for enabling the console to make it a bit simpler and hopefully safer.
[P3RFix_v1.2.5_Xbox_test.zip](https://github.com/user-attachments/files/17481490/P3RFix_v1.2.5_Xbox_test.zip)
[P3RFix_v1.2.5_Steam_test.zip](https://github.com/user-attachments/files/17481532/P3RFix_v1.2.5_Steam_test.zip)

**Comment by slapjd** [comment]
> Can you try this test build? I've reworked the code for enabling the console to make it a bit simpler and hopefully safer. [P3RFix_v1.2.5_Xbox_test.zip](https://github.com/user-attachments/files/17481490/P3RFix_v1.2.5_Xbox_test.zip) [P3RFix_v1.2.5_Steam_test.zip](https://github.com/user-attachments/files/17481532/P3RFix_v1.2.5_Steam_test.zip)

Just tried it now. As far as I can tell nothing has changed. It still crashes almost every time but when it does launch the console can be used. P3RFix log from the crashed game is attached in case it helps. I can upload the log produced by proton if that's helpful, but it is very large (~2MB of text).
[P3RFix.log](https://github.com/user-attachments/files/17482379/P3RFix.log)

**Comment by Lyall** [comment]
> > Can you try this test build? I've reworked the code for enabling the console to make it a bit simpler and hopefully safer. [P3RFix_v1.2.5_Xbox_test.zip](https://github.com/user-attachments/files/17481490/P3RFix_v1.2.5_Xbox_test.zip) [P3RFix_v1.2.5_Steam_test.zip](https://github.com/user-attachments/files/17481532/P3RFix_v1.2.5_Steam_test.zip)
> 
> Just tried it now. As far as I can tell nothing has changed. It still crashes almost every time but when it does launch the console can be used. P3RFix log from the crashed game is attached in case it helps. I can upload the log produced by proton if that's helpful, but it is very large (~2MB of text). [P3RFix.log](https://github.com/user-attachments/files/17482379/P3RFix.log)

Hmm that's interesting. It's not crashing during/after console creation according to the logs, yet disabling the console option in `P3RFix.ini` consistently fixes this issue?

**Comment by slapjd** [comment]
Yep, I haven't had it crash with the console off at all.
My only guess is that something *else* doesn't like the console being made too early? If nobody has had the issue on Windows it could be related to WINE doing something differently?
I did try a few different proton versions but they all have the same result fwiw

**Comment by Lyall** [comment]
> Yep, I haven't had it crash with the console off at all. My only guess is that something _else_ doesn't like the console being made too early? If nobody has had the issue on Windows it could be related to WINE doing something differently? I did try a few different proton versions but they all have the same result fwiw

That's very odd. I can't think of what would be causing crashing related to console creation. If it's not crashing during the creation process, then I frankly have no idea what could be happening. 

The only thing that I can think of that may make a difference is a configurable delay before running most of the code/hooks. I've added an injection delay parameter to `P3RFix.ini` in this test build. By default it's set to 1000ms. You could try experimenting with increasing that value if the 1 second delay doesn't help. 
[P3RFix_v1.2.5_Steam_test2.zip](https://github.com/user-attachments/files/17518755/P3RFix_v1.2.5_Steam_test2.zip)

If this doesn't work then unfortunately I'm pretty much out of ideas, it may just have to be a known issue with enabling the console and running Proton.

**Comment by slapjd** [comment]
Delaying the injection doesn't seem to help anything, so I guess it's safe to assume this is some weird proton interaction I guess unless someone starts having the problem on Windows 🤷.

**Comment by lonewolfe92** [comment]
> ## Issue Summary:
> The game crashes at startup showing the UE crash reporter when using the mod. I can run the game normally when not using the mod by excluding the `WINEDLLOVERRIDES="dsound=n,b" %command%` launch option.
> 
> ![image](https://private-user-images.githubusercontent.com/24415505/368311742-db96f6a3-75bc-4deb-91fb-e7ef0e34ac58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0Mjk3MjcsIm5iZiI6MTczNjQyOTQyNywicGF0aCI6Ii8yNDQxNTUwNS8zNjgzMTE3NDItZGI5NmY2YTMtNzViYy00ZGViLTkxZmItZTdlZjBlMzRhYzU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA5VDEzMzAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMmM1ZDJhMzJmMDUwNzhiNmM3MzZjMzIxZDRhMWJhMGZlNDBiNTIxNjEyNmRiZjFiYTdkZWU0YzljYzYxM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-hvlkz7GA83Wd5aT9JWOi9hmS-lZJpFP7rs8ItUVsCs)
> 
> ## P3RFix & Game Version Numbers:
> Tried v1.2.2 and v1.2.3 of P3RFix and using the latest game version.
> 
> ## Log Files:
> [P3RFix.log](https://github.com/user-attachments/files/17034139/P3RFix.log)
> 
> I'm using a 7800X3D and an RX 7900XT on Linux.
> 
> ## Reproduction:
> 1. Click on Launch button in Steam
> 2. Game crashes and UE4 crash reporter opens

Something similar is happening to me on the latest release. It only runs when deleting the dsound DLL. Not sure why, but not even disabling console wouldnt launch the game, it’d just freeze on starting. I’m on windows rtx 4060
